.TH MINORG 1 "26 February 2021"
.SH NAME
minorg \- identifies minimum set of gRNAs required to target desired sequences


.SH SYNOPSIS
.B minorg
{\fB-f\fI file\fR|\fB-q\fI file\fR|[{\fB\-g\fI string\fR|\fB\-c\fI string\fR} \fB\-a\fI string\fR]}
[\fIOPTION\fP]\&.\|.\|.\&


.SH DESCRIPTION
.B minorg
identifies the minimum set of gRNA sequences required to target desired sequences. Desired sequences can be (1) provided in a FASTA file or (2) specified using a combination of accession number AND gene IDs or cluster names. If (2), complete CDS sequences of genes of interest will be extracted and used as query for a discontiguous blastn search against Van de Weyer et al.'s (2019) immune genes RenSeq contigs, filtered for desired accessions. Overlapping BLAST hits will be merged and treated as targets for gRNA identification. These target sequences can also be further narrowed down to only specific domains. Non-target sequences of the desired accessions will be used to identify potential off-target effects.
.TP
Note that this programme can only distinguish introns and exons based on reference GFF annotations. Manual curation may be required to assess suitability of candidate gRNA.
.TP
Note that unless otherwise specified, this programme searches Van de Weyer et al.'s (2019) RenSeq dataset for gene homologues.
.SS Exit status:
.TP
.B 0
if OK,
.TP
.B 1
if arguments are invalid,
.TP
.B 2
if no homologues are found.


.SH OPTIONS

.SS Generic Programme Information
.TP
.B \-h "," \-\-help
Print this manual and exit.
.TP
.B \-\-readme
Print README file containing information on input and output formats.
.TP
.B \-v "," \-\-version
Print programme version and exit.

.SS Lookups
.TP
.B \-\-accessions
Print <accession ID>,<accession name> of available accessions in Van de Weyer et al.'s (2019) RenSeq dataset and exit.
.TP
.B \-\-aliases
Print domains in each cluster and cluster alias(es) and exit.
.TP
.B \-\-members \fI string
Print gene IDs of members in user-specified cluster and exit.
Sample execution: minorg --members DM2

.SS Execution Control
.TP
.B \-\-auto
Skips manual checking of gRNA sequences.

.SS Output Control
.TP
.B \-d "," \-\-dir \fI path
Specifies directory to write output files into.
Temporary files will also be generated in this directory.
.TP
.B \-\-prefix \fI string
Prefix to prepend to directories and files generated by minorg.
Default is minorg.

.SS Target Sequence Options
.TP
.B \-t "," \-\-target \fI file
Specifies FASTA file of target sequences.
Should NOT be used with -q/--query, -f/--fasta.
.\" cheat indentation
.TP
.B "" 
When used with -i/--input or -a/--acc, the specified accessions from Van de Weyer et al.'s (2019) RenSeq database will be used for background screening.
.\" cheat indentation
.TP
.B "" 
When used with --screen-ref and [ -c/--cluster or -g/--gene ], the relevant genes will be masked during reference screening.
.\" cheat indentation
.TP
.B "" 
When used with [ -i/--input or -a/--acc ] and [ -g/--gene or -c/--cluster ], the homologues of the specified genes/clusters will be inferred using the same algorithm for discovering targets, and these homologues will then be masked in Van de Weyer et al.'s (2019) RenSeq database during background screening of the specified accessions. The same options used for defining targets in non-reference queries (such as --minlen and --minid) can be used to define non-reference homologues for masking.
.TP
.B \-q "," \-\-query \fI file
Specifies FASTA file of sequences in which to search for target sequences.
I.e. This file will replace the Van de Weyer et al.'s (2019) RenSeq database when searching for homologues.
Should NOT be used with -t/--target.
.\" cheat indentation
.TP
.B "" 
When used with -i/--input or -a/--acc, the specified accessions from Van de Weyer et al.'s (2019) RenSeq database will be used for background screening.
.\" cheat indentation
.TP
.B "" 
When used with --screen-ref and [ -c/--cluster or -g/--gene ], the relevant genes will be masked during reference screening.
.\" cheat indentation
.TP
.B "" 
When used with [ -i/--input or -a/--acc ] and [ -g/--gene or -c/--cluster ], the homologues of the specified genes/clusters will be inferred using the same algorithm for discovering targets, and these homologues will then be masked in Van de Weyer et al.'s (2019) RenSeq database during background screening of the specified accessions. The same options used for defining targets in non-reference queries (such as --minlen and --minid) can be used to define non-reference homologues for masking.
.TP
.B \-c "," \-\-cluster \fI string
Cluster name or alias.
Each cluster will be processed separately and written to separate sub-folders.
Sub-folder names follow the convention: <prefix>_<cluster name>.
Should NOT be used with -g/--gene.
Should NOT be used with -t/--target or -q/--query unless also used with [ --screen-ref and [ -g/--gene or -c/--cluster] ] OR [ [ -i/--input or -a/--acc ] and [ -g/--gene or -c/--cluster] ] (and --skip-bg-check is NOT raised).
See /mnt/chaelab/rachelle/data/NLR/clusters/cluster_aliases.txt for supported aliases. If the cluster of interest is not in the file, you can provide gene IDs of genes within the cluster of interest using -g/--gene.
.TP
.B \-g "," \-\-gene \fI string
Standard ORF name (e.g. AT1G01010).
Supports comma-separated multi-gene input (e.g. AT1G01010,AT1G01020,AT1G01030). No spaces allowed.
Supports file input, where file contains gene names delimited by newline.
Should NOT be used with -c/--cluster.
Should NOT be used with -t/--target or -q/--query unless also used with [ --screen-ref and [ -g/--gene or -c/--cluster] ] OR [ [ -i/--input or -a/--acc ] and [ -g/--gene or -c/--cluster] ] (and --skip-bg-check is NOT raised).
.TP
.B \-a "," \-\-acc \fI string
Accession number (e.g. 10015). Accession names are NOT supported.
Supports comma-separated multi-accession input (e.g. 6909,10013,10015). No spaces allowed.
Only accessions represented in Van de Weyer et al.'s (2019) dataset can be processed.
If used with -t/--target or -q/--query, the specified accession(s) will be used to check for off-targets.
.TP
.B \-i "," \-\-input \fI file
Specifies text file containing accession numbers (accession names are NOT supported) delimited by newline.
Only accessions represented in Van de Weyer et al.'s (2019) dataset can be processed.
If used with -t/--target or -q/--query, the specified accession(s) will be used to check for off-targets.
.TP
.B \-\-domain \fI string
Name or CDD PSSM-Id of a domain to restrict sequences to.
To specify a domain that does not currently have domain name support, please use its CDD PSSM-Id.
Note that it is the responsibility of the user to ensure that the specified domain exists in the genes specified by -g/--gene or -c/--cluster. This programme does not check if the domain exists before running.
Will be ignored if -t/--target is used.
Currently supported domain names and corresponding mappings to PSSM-Ids:
        TIR: 366714
        CC, RX-CC_like: 392282
        Rx_N: 375519
        RPW8: 384063
        NBS, NB-ARC: 391514
.TP
.B \-\-db \fI path
Specifies blast database used to search for domains.
Default database is CDD.v.3.18 (installed at /mnt/chaelab/shared/blastdb/Cdd.v3.18/Cdd).
Will be ignored if --domain is not used.
.TP
.B \-\-minlen \fI number
Minimum length (bp) merged sequences required to meet to be retained as gRNA targets.
Will be ignored if -t/--target is used.
Default is 0.
.TP
.B \-\-minid \fI number
Minimum identity (%) that the hit with the highest identity in a merged sequence is required to meet for the merged sequence to be retained as a gRNA target.
Will be ignored if -t/--target is used.
Default is 0.
.TP
.B \-\-merge\-within \fI number
Maximum allowable distance (bp) between non-overlapping hits for merging. If hits are within this distance, they will be merged.
May be important if large insertions into non-reference accessions are suspected.
Will be ignored if -t/--target is used.
Default is 100.
.TP
.B \-\-check\-id\-before\-merge
Removes hits that do not meet the minimum identity specified by --minid before merging hits into single target sequences.
If not raised, overlapping hits (or hit with a distance between them less than the value specified by --merge-within) will be merged before filtering out sequences that only do not contain any hit thats meet the minimum identity specified by --minid.
Will be ignored if -t/--target is used.
.TP
.B \-\-check\-reciprocal "," \-\-check\-recip
Checks potential target sequences against the reference genome. Only potential target sequences which best alignment (per bit score) is to any of the genes of interest (specified by -g/--gene or -c/--cluster) will be retained.
.TP
.B \-\-relax\-reciprocal "," \-\-relax\-recip
Relax reciprocal check so that candidate targets that overlap with non-target genes will be accepted so they also overlap with the best bitscore with a target gene. This is especially relevant if the target gene overlaps with a non-target gene (e.g. a pseudogene); raising this flag will allow the overlap to NOT be treated as off-target. If used, --check-reciprocal will be automatically raised.

.SS gRNA Options
.TP
.B \-p "," \-\-pam \fI string
PAM sequence.
Spacer position 'N' does not need to be specified.
Default is GG.
.TP
.B \-l "," \-\-length \fI number
gRNA length in bp (excluding N + PAM).
Default is 20.
.TP
.B \-s "," \-\-sets \fI number
Number of mutually exclusive gRNA sets to output.
Default is 1.
.TP
.B \-\-mismatch \fI number
Candidate gRNA sequences that have the same or fewer number of mismatches than the specified value in a non-target sequence will be categorised as non-specific and excluded.
Default is 0.
.TP
.B \-\-gap \fI number
Candidate gRNA sequences that have the same or fewer number of gaps than the specified value in a non-target sequence will be categorised as non-specific and excluded.
Default is 0.
.TP
.B \-e "," \-\-exclude \fI file
Specifies FASTA file containing gRNA sequences to exclude.
.TP
.B \-b "," \-\-background \fI file
Specifies FASTA file containing sequences to search against for off-target hits.
Overrides default behaviour, where the query file (-q/--query/-f/--fasta if specified, otherwise the relevant accessions from Van de Weyer et al.'s (2019) RenSeq dataset) is used to search for off-target hits.
.TP
.B \-\-sc\-algorithm \fI string
Specifies set cover algorithm used to identify final set of gRNA candidates that cover all target sequences.
No performance differences are expected between algorithms for small datasets.
Options include: LAR, greedy.
Default is LAR.
.TP
.B \-\-skip\-bg\-check
Skip the background checking step that screens for off-targets.
.TP
.B \-\-screen\-ref
Mask the gene specified by -g/--gene in the reference genome (specified by --reference, see relevant entry in this manual for default value) and search for gRNA off-target hits in the rest of the genome. Candidate gRNA with off-target hits in unmasked regions of the genome will be categorised as non-specific and excluded.
.TP
.B \-\-unmask\-ref
Skip the masking of the gene specified by -g/--gene in the reference genome (specified by --reference, see relevant entry in this manual for default value) when screening for off-target hits in the reference genome.
Will be ignored if --screen-ref is not used.
.TP
.B \-\-relax
Accept gRNA that are mapped to a gap in the reference gene as long as the gap is within a coding region.

.SS Lookup Files Control
.TP
.B \-b "," \-\-bed \fI file
Specifies BED file derived from GFF3 file from which to extract reference feature ranges.
Default is Arabidopsis thaliana TAIR10 annotations.
.TP
.B \-r "," \-\-reference \fI file
Specifies FASTA file of a reference genome from which to extract reference feature sequences.
Default is Arabidopsis thaliana TAIR10 assembly.
.TP
.B \-\-extend\-genome \fI file
Specifies FASTA file of genomic sequence of genes that will be used to extend the reference genome. Must be sense strand.
Must be used with --extend-cds.
.TP
.B \-\-extend\-cds \fI file
Specifies FASTA file of CDS sequences that will be used to extend the reference genome. Must be sense strand.
Multiple variants per gene are allowed.
Must be used with --extend-genome.
Sequences in this file must be named according to: <gene name in --extend-genome file>.<variant number>
.TP
.B \-\-cluster\-lookup \fI file
Specifies a space-delimited text file where row 1 is a header (fname domains aliases), and subsequent rows follow the following format: column 1 specifies newline-delmited text file of standard gene ORF names, column 2 specifies semi-colon-delimited domain names, and column 3 specifies semi-colon-delimited cluster aliases.
This file is used to look up members of clusters according to their cluster aliases when -c/--cluster is used.
.TP
.B \-\-cluster\-dir \fI dir
Specifies a directory containing newline-delimited files of standard gene ORF names, from which gene IDs can be extracted when -c/--cluster is used.

.SH EXAMPLES
.TP
1. Find gRNA sequences based on the provided FASTA file ('/mnt/chaelab/some_user/some_seqs.fasta'), using a single accession (10015) as background to test for off-target hits, and write output files into the current working directory.

minorg -t /mnt/chaelab/some_user/some_seqs.fasta -a 10015 -d $(pwd)

.B OR

minorg --target /mnt/chaelab/some_user/some_seqs.fasta --acc 10015 --dir $(pwd)

.TP
2. Extract the specified domain (TIR) of multiple genes (AT3G44400,AT3G44480,AT3G44630,AT3G44670) from multiple accessions (6909,10015) and find gRNAs among all genes from all accessions using multiple accessions (6909,10015) as background to test for off-target hits (i.e. any candidate gRNA that has off-target hits in at least one accession will be excluded). gRNA sequences found in the specified file of sequences to exclude ('/mnt/chaelab/some_user/undesired_seqs/fasta') will be excluded. Write output files to the specified directory ('/mnt/chaelab/some_user/some_dir').

minorg -g AT3G44400,AT3G44480,AT3G44630,AT3G44670 -a 6909,10015 -d /mnt/chaelab/some_user/some_dir --domain TIR -e /mnt/chaelab/some_user/undesired_seqs.fasta

.B OR

minorg --gene AT3G44400,AT3G44480,AT3G44630,AT3G44670 --acc 6909,10015, --dir /mnt/chaelab/some_user/some_dir --domain TIR --exclude /mnt/chaelab/some_user/undesired_seqs.fasta

.TP
3. Extract the specified domain (307630, the CDD PSSM-Id for TIR) of genes in a specified cluster (DM2, which maps to RPP1) from a single accession (10015) and filter the extracted sequences for user-specified minimum length (300, instead of the default 0) and percentage identity (90, instead of the default 0). Find gRNAs among filtered sequences from all accessions, using the specified FASTA file ('/mnt/chaelab/some_user/some_bg_seqs.fasta') as background to test for off-target hits, and write output files to the specified directory ('/mnt/chaelab/some_user/some_dir')

minorg -c DM2 -a 10015 -d /mnt/chaelab/some_user/some_dir -b /mnt/chaelab/some_user/some_bg_seqs.fasta --domain 307630 --minlen 300 --minid 90

.B OR

minorg --cluster DM2 --acc 10015 --dir /mnt/chaelab/some_user/some_dir --background /mnt/chaelab/some_user/some_bg_seqs.fasta --domain 307630 --minlen 300 --minid 90

.TP
4. Extract the specified domain (TIR) from genes in multiple clusters (DM2,RPP2) from a single accession (10015) and merge sequences that are closer to each other than the user-specified distance in base pairs (300). Find gRNAs among the merged sequences from all accessions, using the user-specified PAM sequence (G) to define positions of gRNAs and using a single accession (10015) as background to test for off-target hits, filtering out gRNAs that align with non-target sequences with the same or fewer mismatches (1, instead of the default 0) and gaps (1, instead of the default 0) than the user-specified values. Write output files to the specified directory ('/mnt/chaelab/some_user/some_dir') and prepend the specified prefix ('project') to output files and directories generated.

minorg -c DM2,RPP2 -a 10015 -d /mnt/chaelab/some_user/some_dir --domain TIR --merge-within 300 -p G --mismatch 1 --gap 1 --prefix project

.B OR

minorg --cluster DM2,RPP2 --acc 10015 --dir /mnt/chaelab/some_user/some_dir --domain TIR --merge-within 300 --pam G --mismatch 1 --gap 1 --prefix project

.TP
5. Extract the specified domain (TIR) from genes in multiple clusters (DM2,RPP2) from unknown sequences in a fasta file ('/mnt/chaelab/some_user/some_genome.fasta') and merge sequences that are closer to each other than the user-specified distance in base pairs (300). Find gRNAs among the merged sequences from the unknown sequences using the user-specified PAM sequence (G) to define positions of gRNAs and using a single accession (10015) as background to test for off-target hits, filtering out gRNAs that align with non-target sequences with the same or fewer mismatches (1, instead of the default 0) and gaps (1, instead of the default 0) than the user-specified values. Write output files to the specified directory ('/mnt/chaelab/some_user/some_dir') and prepend the specified prefix ('project') to output files and directories generated.

minorg -q /mnt/chaelab/some_user/some_genome.fasta -c DM2,RPP2 -a 10015 -d /mnt/chaelab/some_user/some_dir --domain TIR --merge-within 300 -p G --mismatch 1 --gap 1 --prefix project

.B OR

minorg --query /mnt/chaelab/some_user/some_genome.fasta --cluster DM2,RPP2 --acc 10015 --dir /mnt/chaelab/some_user/some_dir --domain TIR --merge-within 300 --pam G --mismatch 1 --gap 1 --prefix project


.SH AUTHOR
Written by Rachelle Lee and conceptualised by Rachelle Lee and Cher Wei Yuan


.SH REPORTING BUGS
Report bugs to e0336214@u.nus.edu
